package CourierPD;

import java.util.*;

/**
 * The report which details how well an individual courier or multiple couriers performed during a given period. This report is for internal Acme Courier Services use and contains data which should not be shared with clients. Extends the abstract Report Class.
 */
public class CourierPerformanceReport extends Report {

    /**
     * The couriers required for creating the report. If there is only one courier, then the report details information only for that courier. If multiple couriers are included, then the report is generated by looping through each courier.
     */
    private Collection<Courier> courier;

    public Collection<Courier> getCourier() {
        return this.courier;
    }

    public void setCourier(Collection<Courier> courier) {
        this.courier = courier;
    }

    /**
     * The default constructor of the courier performance report. After the reporting object is made, it relies on methods inherited from its parent in order to produce the report.
     */
    public CourierPerformanceReport() {
        // TODO - implement CourierPerformanceReport.CourierPerformanceReport
        throw new UnsupportedOperationException();
    }

    /**
     * Creates the report required. This method should be overridden in the subclasses to provide the specific details and form of a given report.
     */
    public void generate() {
        // TODO - implement CourierPerformanceReport.generate
        throw new UnsupportedOperationException();
    }

}